# -*- coding: utf-8 -*-
"""Line.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-PtsmmEBdysbi-9Urx63pTqnNLRxocZ
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

import subprocess
import shlex

plt.axis([-3,6,-3,6])

plt.axis('on')
plt.grid(True)


x1 = np.arange(-12,12)
y1= (3*x1 +6)/4 
x2 = np.arange(-12,12)
y2= 9-3*x2
x3 = np.arange(-12,12)
y3= x3*0
plt.plot(x1,y1,label='3x-4y+6=0',linewidth=2,color='y')
plt.plot(x2,y2,label='3x+y-9=0',linewidth=2,color='g')
plt.plot(x3,y3,label='y=0',linewidth=2,color='b')


plt.text(2,3,'P(2,3)')
plt.text(-2,0,'Q(-2,0)')
plt.text(3,0,'R(3,0)')

plt.savefig('line.pdf')
plt.show()