# -*- coding: utf-8 -*-
"""Line.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-PtsmmEBdysbi-9Urx63pTqnNLRxocZ
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

plt.axis([-3,6,-3,6])

plt.axis('on')
plt.grid(True)

def f(x1):
    return (3*x1 +6)/4

x1 = np.arange(-12,12)    
y1 = np.zeros(len(x1))        
for i in range(len(x1)):
    y1[i] = f(x1[i])

plt.plot(x1,y1,label='3x-4y+6=0',linewidth=2,color='y')

def f(x2):
    return 9-3*x2

x2 = np.arange(-12,12)    
y2 = np.zeros(len(x2))        
for i in range(len(x2)):
    y2[i] = f(x2[i])

plt.plot(x2,y2,label='3x+y-9=0',linewidth=2,color='g')

def f(x3):
    return x3*0

x3 = np.arange(-12,12)    
y3 = np.zeros(len(x3))        
for i in range(len(x3)):
    y3[i] = f(x3[i])

plt.plot(x3,y3,label='y=0',linewidth=2,color='b')

A = np.array([[3,-4],
 [3, 1]])
B = np.array([-6,9]) 
P = np.linalg.solve(A, B) 

C = np.array([[3,-4],
 [0, 1]])
D = np.array([-6,0]) 
Q = np.linalg.solve(C, D) 

E = np.array([[3,1],
 [0, 1]])
F = np.array([9,0]) 
R = np.linalg.solve(E, F) 


plt.text(P[0],P[1],'P')
plt.text(Q[0],Q[1],'Q')
plt.text(R[0],R[1],'R')

plt.savefig('line.pdf')
plt.show()